#pragma once













enum DIR	{ DIR_LEFT, DIR_RIGHT, DIR_UP, DIR_DOWN, DIR_END };	

enum OBJID{ OBJ_BUTTON, OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_FYING_MONSTER, OBJ_METERIAL, OBJ_METERIAL_MOVE, OBJ_ITEM,OBJ_HEART,
	OBJ_ITEM_BULLET, OBJ_MOUSE, OBJ_FAMILIAR, OBJ_SHIELD, OBJ_MONSTER_BULLET, OBJ_BOMB, OBJ_EXPLOSION, OBJ_EFFECT, 
	OBJ_UI, OBJ_WALL, OBJ_DOOR, OBJ_END};

enum RENDERID { BACKGROUND, MONSTER,GAMEOBJECT,FLYMONSTER, FAMILIAR ,PLAYER, EFFECT, UI, RENDER_END };

enum SCENEID { SCENE_LOGO, SCENE_MENU, SCENE_EDIT, SCENE_STAGE, SCENE_SHOP, SCENE_CREDIT, SCENE_EMPTY, SCENE_END };

 // 최대 32 채널까지 동시 재생이 가능
enum CHANNELID { SOUND_BGM, SOUND_PLAYER,SOUND_ITEM_EFFECT, SOUND_EXPLOSION,
	SOUND_KEY, SOUND_BOMB, SOUND_HEART,SOUND_COIN, SOUND_MONSTER, 
	SOUND_EFFECT, SOUND_ITEM, SOUND_UI, MAXCHANNEL };

enum STATE { IDLE, ATTACK_DOWN, ATTACK_RIGHT, ATTACK_UP, ATTACK_LEFT, HIT, USE_ITEM, DEAD, END };
